add_library(provider INTERFACE)
target_include_directories(provider INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)

add_library(digital_input_provider INTERFACE)
target_include_directories(digital_input_provider INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(digital_input_provider INTERFACE provider)

add_library(digital_output_provider INTERFACE)
target_include_directories(digital_output_provider INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(digital_output_provider INTERFACE provider)